### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by shshaw**
Rewrite of the script to:
- Remove jQuery dependency
- Better performance with `requestAnimationFrame` and event throttling
- Options parameter
- Smooth animation (damping option)
- Reset on `mouseleave`
- Responsive ( element size updated  on window resize )
- Minified version (from [Closure
  Compiler](http://closure-compiler.appspot.com/home))

### CODE REVIEW

**Comment by nashvail** [comment]
@shshaw Thanks for the contribution! I really appreciate it.

**Comment by nashvail** [comment]
@shshaw Thanks!
http://yourreactiongifs.tumblr.com/post/77410306544

**Comment by nashvail** [comment]
@shshaw I am using the BEM methodology https://css-tricks.com/bem-101/ , I think we should stick with it. Also the default max rotation and max translation can be reduced. Since I am using the .js file as an example in the writeup, the older file (one with jQuery as dependency) would be better to have around and I will mention in the article about the improved file. Thanks again for the contribution.

**Comment by shshaw** [comment]
I use BEM as well, and I updated the classes to be more correctly in line with BEM.

`.icon` is the block.
`.icon--settings` is the modifier for the `.icon` block that gives it the appropriate styling.
`.icon__shadow` is an element that's dependent on the `.icon` block.

Before, you seemed to have the `--` and `__` reversed.

**Comment by shshaw** [comment]
I also removed the SASS file because most of the items you were using `%extend` for worked by just having the appropriate BEM class in place.

**Comment by nashvail** [comment]
You're right, my bad. I actually do have `--` and `__` reversed. Don't you think something like `icon--settings__cog1` is more readable than `icon__cog1` ?

**Comment by shshaw** [comment]
That's one thing I wasn't sure about, how to handle was the individual icon's elements ( the cogs, 'tv shows', music note, etc. ). There aren't really any common styles between all of those, so it didn't make sense to have an element class for them ( `.icon__element`, `.icon__element--cog1` ).

With strict BEM, I don't think you can have an element class that's dependent on a modifier, like `.icon--settings__cog1`.

**Comment by shshaw** [comment]
Regarding the article, the only specific mentions in the content that are different in the original versus my rewrite are:
- `maxTransform` and `maxRotation` are now in the `options` parameter vs hardcoded.
- `data-stacking-factor` is now `data-stacking` to keep things shorter, though this is easy to change back if you want to keep it `data-stacking-factor`
- `ATicon` is called directly to initiate instead of `ATicon.getInstance`
- jQuery elements are not used
- The script is now more than 50 lines of code, due to the dropping of jQuery, adding options, and damping effect. :-)

The math is kept all the same. That's not my strong suit, so I'm quite thankful you figured that all out :-)

**Comment by nashvail** [comment]
Makes sense, is it possible to have all the improvements you made work side by side with the current ATicons.js file? Because I think those interested in the math would find it easier to decipher the code in the current file. It should only take some changes to the css class names for that to happen ... I guess.

**Pull request merged**
